# Generated by Django 4.2.4 on 2023-09-06 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('58f2f51a-289b-4019-9fdb-4afc59f76126'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_varient', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SizeVarient',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('58f2f51a-289b-4019-9fdb-4afc59f76126'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size_variant', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('58f2f51a-289b-4019-9fdb-4afc59f76126'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('58f2f51a-289b-4019-9fdb-4afc59f76126'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('58f2f51a-289b-4019-9fdb-4afc59f76126'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color_varient',
            field=models.ManyToManyField(to='product.colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(to='product.sizevarient'),
        ),
    ]
