# Generated by Django 4.2.4 on 2024-01-05 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvariant_sizevarient_alter_category_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizevarient',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1bba9293-014a-4995-9c5b-f0b78d2aafd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1bba9293-014a-4995-9c5b-f0b78d2aafd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1bba9293-014a-4995-9c5b-f0b78d2aafd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1bba9293-014a-4995-9c5b-f0b78d2aafd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1bba9293-014a-4995-9c5b-f0b78d2aafd4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
