# Generated by Django 4.2.4 on 2024-01-05 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_uid_alter_colorvariant_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e86be0e8-2e1e-443f-a527-153820ce4e5f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e86be0e8-2e1e-443f-a527-153820ce4e5f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e86be0e8-2e1e-443f-a527-153820ce4e5f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e86be0e8-2e1e-443f-a527-153820ce4e5f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e86be0e8-2e1e-443f-a527-153820ce4e5f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
